### Vamos usar o KNN aqui no python!

#### Utilizaremos o famoso Iris Dataset para aplicar esse modelo
https://scikit-learn.org/stable/datasets/toy_dataset.html#iris-dataset

![alt_text](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Machine+Learning+R/iris-machinelearning.png)

<br>

Baseado nas características da pétala, vamos tentar determinar qual o tipo de Íris ela é!

In [4]:
# importando os dados

from sklearn.datasets import load_iris

In [5]:
# vamos separar os dados entre treino e teste, 
# entao vamos importar a função que faz isso

from sklearn.model_selection import train_test_split

In [6]:
# importando o KNN

from sklearn.neighbors import KNeighborsClassifier

In [7]:
df = load_iris(as_frame = True)['data']
df['type'] = load_iris(as_frame = True)['target']

df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),type
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [8]:
df.groupby('type').describe()['sepal length (cm)']

      count   mean       std  min    25%  50%  75%  max
type
0      50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
1      50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
2      50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

In [9]:
df.groupby('type').describe()['petal width (cm)']

      count   mean       std  min  25%  50%  75%  max
type
0      50.0  0.246  0.105386  0.1  0.2  0.2  0.3  0.6
1      50.0  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
2      50.0  2.026  0.274650  1.4  1.8  2.0  2.3  2.5

In [10]:
# característica da pétala 
X = load_iris(as_frame = True)['data']

# tipo de íris
y = load_iris(as_frame = True)['target']

Vamos usar X de treino e y de treino para treinar o nosso modelo e X de teste e y de teste para testar se o nosso modelo ta acertando bem

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [14]:
# algoritmo sem dados nenhum, onde K = 3

neigh = KNeighborsClassifier(n_neighbors=3)

In [15]:
# treinando o algoritmo

neigh.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [16]:
# usando nosso algoritmo já treinado para fazer previsões usando os dados de teste

y_pred = neigh.predict(X_test)

y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

Vamos ver a quantidade de casos em que erramos

In [17]:
print("Número de íris que previmos errado de um total de {0} observações de teste: {1}"\
      .format(X_test.shape[0], (y_test != y_pred).sum()))

Número de íris que previmos errado de um total de 38 observações de teste: 1

In [18]:
109/120

0.9083333333333333

### Agora, vamos deixar os dados com a mesma média e mesma variância

In [19]:
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
X_train.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [21]:
# algoritmo sem dados nenhum, onde K = 3

neigh = KNeighborsClassifier(n_neighbors=3)

In [ ]:
# treinando o algoritmo

neigh.fit(X_train, y_train)

In [ ]:
# usando nosso algoritmo já treinado para fazer previsões usando os dados de teste

y_pred = neigh.predict(X_test)

y_pred

In [ ]:
print("Número de íris que previmos errado de um total de {0} observações de teste: {1}"\
      .format(X_test.shape[0], (y_test != y_pred).sum()))

In [ ]:
113/120

#### E qual seria o melhor valor de K?

In [ ]:
percentual_acerto = []
tamanho_teste = X_test.shape[0]


for i in range(1, 15):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred_i = knn.predict(X_test)
    
    acerto_i = (y_test == pred_i).sum()/tamanho_teste
    percentual_acerto.append(100 * acerto_i)

In [ ]:
import pandas

In [ ]:
df_acerto = pandas.DataFrame()
df_acerto["K"] = range(1, 15)
df_acerto["percentual_acerto"] = percentual_acerto

In [ ]:
df_acerto.head()

In [ ]:
import plotly.express as px

In [ ]:
fig = px.line(df_acerto, x="K", y="percentual_acerto",
              title='Percentual de Acerto por K')
fig.show("notebook")